project:
  type: website
  output-dir: docs

website:
  title: "Samantha J. Werts"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - href: presentations.qmd
        text: Presentations
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
  page-footer:
    background: light
    left:
      - "Copyright 2023, Samantha Werts"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



